{
 "title": "DevOps",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"devops\"}",
     "legendFormat": "app"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[30s])",
     "legendFormat": "prometheus"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"devops\"}[30s])",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "App Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" }
   ]
  }
 ]
}