- name: Playbook
  become_user: root
  tasks:
  - name: update dependcies
      ap-get:
        update: yes
    - name: install pip
      apt-get:
        name: pip3
        state: latest
    - name: install python_dependencies
      pip:
        requirements: ../app/app/requirements.txt   
    - name: Start flask application
      shell: "python3 -m flask run --host=0.0.0.0"
      environment:
        FLASK_APP: /vagrant/app.py
        